import { NextRequest, NextResponse } from "next/dist/server/web/spec-extension/request";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@payzen/database";
import { format } from "date-fns";

export async function GET(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const { searchParams } = new URL(req.url);
    const startDate = searchParams.get("startDate");
    const endDate = searchParams.get("endDate");

    const transactions = await prisma.transaction.findMany({
      where: {
        userId: session.user.id,
        ...(startDate && endDate && {
          date: { gte: new Date(startDate), lte: new Date(endDate) },
        }),
      },
      include: { category: true, creditCard: true },
      orderBy: { date: "desc" },
    });

    const income = transactions.filter(t => t.type === "INCOME").reduce((a, c) => a + Number(c.amount), 0);
    const expense = transactions.filter(t => t.type === "EXPENSE").reduce((a, c) => a + Number(c.amount), 0);

    // Build a simple HTML that can be converted to PDF-like text
    const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body { font-family: Arial, sans-serif; padding: 32px; color: #111; }
  h1 { color: #7c3aed; margin-bottom: 4px; }
  .summary { display: flex; gap: 32px; margin: 24px 0; }
  .summary div { padding: 16px 24px; border-radius: 8px; background: #f3f4f6; }
  .summary .income { color: #16a34a; }
  .summary .expense { color: #dc2626; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th { background: #7c3aed; color: white; padding: 8px 12px; text-align: left; }
  td { padding: 8px 12px; border-bottom: 1px solid #e5e7eb; }
  tr:nth-child(even) td { background: #f9fafb; }
  .income-amt { color: #16a34a; font-weight: 600; }
  .expense-amt { color: #dc2626; font-weight: 600; }
  .footer { margin-top: 32px; font-size: 11px; color: #9ca3af; text-align: center; }
</style>
</head>
<body>
<h1>💜 Payzen</h1>
<p>Transaction Report — ${format(new Date(), "MMMM d, yyyy")}</p>

<div class="summary">
  <div><p>Total Income</p><p class="income">+$${income.toFixed(2)}</p></div>
  <div><p>Total Expenses</p><p class="expense">-$${expense.toFixed(2)}</p></div>
  <div><p>Balance</p><p>$${(income - expense).toFixed(2)}</p></div>
</div>

<table>
  <thead>
    <tr><th>Date</th><th>Description</th><th>Type</th><th>Amount</th><th>Category</th></tr>
  </thead>
  <tbody>
    ${transactions.map(t => `
    <tr>
      <td>${format(new Date(t.date), "MMM d, yyyy")}</td>
      <td>${t.description}</td>
      <td>${t.type}</td>
      <td class="${t.type === "INCOME" ? "income-amt" : "expense-amt"}">${t.type === "INCOME" ? "+" : "-"}$${Number(t.amount).toFixed(2)}</td>
      <td>${t.category?.name || "—"}</td>
    </tr>`).join("")}
  </tbody>
</table>

<div class="footer">Generated by Payzen • ${format(new Date(), "yyyy-MM-dd HH:mm")}</div>
</body>
</html>`;

    return new NextResponse(html, {
      status: 200,
      headers: {
        "Content-Type": "text/html",
        "Content-Disposition": `attachment; filename="payzen-report-${format(new Date(), "yyyy-MM-dd")}.html"`,
      },
    });
  } catch (error) {
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
  }
}
